lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
theme: jekyll-theme-modernist
title: La pagina de Helder Fernandez desde Github
description: estare proveyendo actualizaciones de mis proyectos por este medio
